### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by dventuri** [dventuri/ProjectEuler#1]
- [x] Make TODO list

- **Task001**
- [x] put main code into funtion
- [x] make alternative math implementation
